-- AlterTable
ALTER TABLE "users" ALTER COLUMN "kill_deaths" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "deaths" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "assists" SET DATA TYPE DOUBLE PRECISION;
